### ISSUE TITLE
the member of "executables" in package.yaml should not be fixed to 6.

### ISSUE THREAD

**Issue by matonix** [matonix/atcoder#18]
```yaml
executables:
  a:
    main:                Main.hs
    source-dirs:         a
  b:
    main:                Main.hs
    source-dirs:         b
  c:
    main:                Main.hs
    source-dirs:         c
  d:
    main:                Main.hs
    source-dirs:         d
  e:
    main:                Main.hs
    source-dirs:         e
  f:
    main:                Main.hs
    source-dirs:         f
```

This part should be declared using actual tasks in the problems.
